version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.1
jobs:
  test:
    docker:
      - image: circleci/node
    working_directory: ~/project
    steps:
      checkout
      - run:cd ~/project/function
      - run:npm install
      - run:npm test
  build:
    docker:
      - image: circleci/node
    working_directory: ~/project
    steps:
      - aws-ecr/build-and-push-image:
        path: ~/project
        repo: 867043545815.dkr.ecr.us-east-1.amazonaws.com/fargate-lambda-template
workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
        requires: test
