version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.4
jobs:
  build-deploy:
    docker:
      - image: circleci/node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd ~/project/function && npm install
      - run:
          name: Run Unit Tests
          command: cd ~/project/function && npm test
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          repo: fargate-lambda-template
          tag: latest
workflows:
  version: 2
  build:
    jobs:
      - build-deploy:
          filter:
              only:
                  - master
