version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.4
jobs:
  test:
    docker:
      - image: circleci/node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd ~/project/function && npm install
      - run:
          name: Run Unit Tests
          command: cd ~/project/function && npm test
  build:
    docker:
      - image: circleci/node
    working_directory: ~/project
    steps:
      - aws-ecr/build-and-push-image:
          repo: fargate-lambda-template
          tag: latest
workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
              - test
